### PR TITLE
Html markup

### PR DESCRIPTION
**Pull request by richardoppiyo**
Added html markup as instructed with minimal styles, implemented ES6 import and export with different module files

### CODE REVIEW

**Review by Lordkaito — APPROVED** [review]
Hi @richardoppiyo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-labana** [comment]
@richardoppiyo Hey Richard, I see that this pr has been approved already, why are you requesting another CRR?

**Comment by richardoppiyo** [comment]
> @richardoppiyo Hey Richard, I see that this pr has been approved already, why are you requesting another CRR?

Hello @omar-labana  I don't know what you are talking about. I haven't requested any other CR

**Comment by omar-labana** [comment]
@richardoppiyo Sorry Richard, system fault

**Pull request merged**
